apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blog-frontend.fullname" . }}-config
  labels:
    {{- include "blog-frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.backendApiUrl }}
